# Generated by Django 5.0.6 on 2024-06-27 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador_school', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produtos',
            name='dono',
        ),
        migrations.RemoveField(
            model_name='produtos',
            name='img_produto',
        ),
    ]
